version: '3'

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: DB-laravel
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        container_name: php
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated
        networks:
            - laravel

    composer:
        container_name: composer
        build:
            context: .
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        user: laravel
        entrypoint: ['composer', '--ignore-platform-reqs']
        networks:
            - laravel
